image: node:23

stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - docker build -t my-image .

deploy_job:
  stage: deploy
  script:
    - docker compose up -d
    
build project:
  image: node:23
  script:
    - npm install
    - npm run build
